version: '3'

services:
  web:
    build: .
    working_dir: /app
    command: sh -c "uvicorn backend.main:app --reload --port=80 --host=0.0.0.0"
    ports: 
      - 80:80
    volumes:
      - ./backend:/app/backend